spring:
  application:
    name: discovery-server
  config:
    import: configserver:${CONFIG_SERVER_URL}
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.retry: DEBUG